[package]
name = "master"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "window-create", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
hyper = { version = "1", features = ["server"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
anyhow = "1"
obfstr = "0.4"
tokio = { version = "1", features = ["full"] }
rusqlite = { version = "0.32.1", features = ["bundled"] }
chrono = "0.4"
futures = "0.3"
shared = { path = "../../shared" }
loader_vars = { path = "../../loader_vars" }
client_vars = { path = "../../client_vars" }
server_vars = { path = "../../server_vars" }
lazy_static = "1"
country-emoji = "0.2"
flate2 = "1"
byteorder = "1"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
