[package]
name = "loader"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false
codegen-units = 1
debug-assertions = false
incremental = false
panic = "abort"

[build-dependencies]
rand = "0.8"

[package.metadata.cargo-post.dependencies]
regex = "1"
memmap2 = "0.9"
walkdir = "2"
rand = "0.8"

[dependencies]
lazy_static = "1"
windows-service = "0.7"
windows-service-detector = "0.1"
shared = { path = "../shared" }
loader_vars = { path = "../loader_vars" }
obfstr = "0.4"
anyhow = "1"
serde_json = "1"
tokio = "1"
serde = "1"
