[package]
name = "server_vars"
version = "0.1.0"
edition = "2021"

[lib]
name = "server_vars"
path = "src/lib.rs"

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false
codegen-units = 1
debug-assertions = false
incremental = false
panic = "abort"

[dependencies]
serde = { version = "1", features = ["derive"] }
# shared = { path = "../shared" }
