[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
name = "shared"
path = "src/lib.rs"

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false
codegen-units = 1
debug-assertions = false
panic = "abort"

[build-dependencies]
rand = "0.8.5"

[dependencies]
anyhow = "1.0.95"
rusqlite = { version = "0.32.1", features = ["bundled"] }
arti-client = { version = "0.26.0", features = [
    # "tokio",
    # "native-tls",
    # "async-std",
    # "bridge-client",
    # "memquota",
    "onion-service-client",
    # # "onion-service-service",
    # "pt-client",
    # "anyhow",
    # "compression",
] }
base64 = "0.22.1"
chacha20poly1305 = "0.10.1"
chrono = "0.4.39"
obfstr = "0.4.4"
rand = "0.8.5"
serde = "1.0.217"
serde_json = "1.0.137"
sha2 = "0.10.8"
tokio = "1.43.0"
tor-rtcompat = "0.26.0"
winapi = { version = "0.3.9", features = [
    "processthreadsapi",
    "securitybaseapi",
    "windef",
    "psapi",
    "shellapi",
    "winuser",
    "winbase",
    "winerror",
    "errhandlingapi",
    "handleapi",
    "tlhelp32",
    "winsvc",
    "debugapi",
] }
winreg = "0.55.0"
ureq = "2.12.1"
md5 = "0.7.0"
sysinfo = "0.33.1"
