[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
name = "shared"
path = "src/lib.rs"

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false
codegen-units = 1
debug-assertions = false
incremental = false
panic = "abort"

[build-dependencies]
rand = "0.8"

[dependencies]
anyhow = "1"
rusqlite = { version = "0.32.1", features = ["bundled"] }
arti-client = { version = "0.26", features = [
    # "tokio",
    # "native-tls",
    # "async-std",
    # "bridge-client",
    # "memquota",
    "onion-service-client",
    # # "onion-service-service",
    # "pt-client",
    # "anyhow",
    # "compression",
] }
base64 = "0.22"
chacha20poly1305 = "0.10"
chrono = "0.4"
obfstr = "0.4"
rand = "0.8"
serde = "1"
serde_json = "1"
sha2 = "0.10"
tokio = "1"
tor-rtcompat = "0.26"
winapi = { version = "0.3.9", features = [
    # "processthreadsapi",
    # "securitybaseapi",
    # "windef",
    # "psapi",
    # "shellapi",
    # "winuser",
    # "winbase",
    # "winerror",
    # "errhandlingapi",
    # "handleapi",
    # "tlhelp32",
    # "winsvc",
    # "debugapi",
] }
winreg = "0.55"
ureq = "2"
md5 = "0.7"
sysinfo = "0.33"
flate2 = "1"
byteorder = "1"
